### ISSUE TITLE
TT-001 Login/signup

### ISSUE THREAD

**Issue by DancingPaws** [sw21-tug/Team-04#1]
simple as possible: email, password, username

**Comment by DancingPaws** [comment]
as a user i want my data to be secure that is why i need a login

**Comment by PoojaYeli** [comment]
User story points- 5

**Comment by PoojaYeli** [comment]
When user opens the app, signup/login page should be shown. After signup/login, posts display page should be shown. User should be logged out when he/she closes the app.
