### ISSUE TITLE
TT-010 Post Add

### ISSUE THREAD

**Issue by DancingPaws** [sw21-tug/Team-04#13]
as a user i want to express my ideas. I want them to be saved (in the db) so that i and other users can see them at a latter time as well.
implement after (TT-019 Post Add Display)

**Comment by PoojaYeli** [comment]
Needs user to fill in- description like describing the trip, destination- from and to, min-max people- not mandatory, how long the vacation takes- like 1 week/start date-end date

**Comment by DancingPaws** [comment]
split into designing a box and a functionality (adding to DB)
