### ISSUE TITLE
TT-002 Posts Display Main

### ISSUE THREAD

**Issue by DancingPaws** [sw21-tug/Team-04#6]
display all posts, main page

**Comment by DancingPaws** [comment]
as a user i want to see other posts

**Comment by PoojaYeli** [comment]
User point- 40, so we need to split

**Comment by Freddynator8** [comment]
split in add post, display post , comment post

**Comment by PoojaYeli** [comment]
User points- 5

**Comment by DancingPaws** [comment]
split into design box and functionality
